name: danapp
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # State management
  get_it: ^7.6.4
  get: ^4.6.6
  provider: ^6.1.1

  # Utils

  flutter_screenutil: ^5.0.0+2
  flutter_svg: ^2.0.10+1
  flutter_animate: ^4.5.0
  page_transition: ^2.1.0
  smooth_page_indicator: ^1.1.0
  fl_country_code_picker: ^0.1.9+1




  # local DB
  path_provider: ^2.1.1
  path: ^1.8.3
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  local_auth: ^2.1.7

  # firebase
  firebase_messaging: ^14.7.9
  firebase_core: ^2.24.2
  firebase_in_app_messaging: ^0.7.4+8
  firebase_analytics: ^10.7.4
  firebase_dynamic_links: ^5.4.8


  # connectivity
  http: ^1.1.0
  http_parser: ^4.0.2
  permission_handler: ^10.2.0
  diox: ^5.0.0
  logger: ^2.0.2+1

  #functionalities
  intl: ^0.18.1
  pin_code_fields: ^8.0.1
  rename_app: ^1.5.0
  animated_bottom_navigation_bar: ^1.3.3
  
  clipboard: ^0.1.3
  
  

  #loading effect
  redacted: ^1.0.11
  loader_overlay: ^4.0.0
  #toast
  toastification: ^2.0.0
  dashed_circular_progress_bar: ^0.0.6

  

 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/images/mobile/
    - assets/svg/
  #    - assets/resources/
  fonts:
    - family: Mark
      fonts:
        - asset: assets/fonts/Mark-Bold.ttf
        - asset: assets/fonts/Mark-Light.ttf
        - asset: assets/fonts/Mark-Medium.ttf
        - asset: assets/fonts/Mark-Regular.ttf


 