import '../../res/import/import.dart';

/// constant colors
const Color danappTransparent = Colors.transparent;
const Color danappBlack = Colors.black;
const Color danappRed = Colors.red;
const Color danappGrey = Color(0xff98A2B3);
const Color danappWhite = Colors.white;
const Color danappGreen = Colors.green;
const Color danappBackgroundColor =  Colors.white;

const Color danappPrimaryColor = Color(0xff217AC0);
const Color danappSecondaryColor = Color(0xffFFC300);
const Color danappTertiaryColor = Color(0xffF4D0D9);
const Color danappTextColor = Color(0xff1E1E1E);
const Color danappHintTextColor = Color(0xff1E1E1E);
const Color danappFillColor = Color(0xffF9FAFB);
const Color danappSubColor = Color(0xffFEFEFE);
const Color danappColor1 = Color(0xffC4C4C4);
const Color danappColor2 = Color(0xffDADADA);
const Color danappColor3 = Color(0xffF4F4F6);
const Color danappColor4 = Color(0xffE9EBEE);
const Color danappColor5 = Color(0xffB1B0B0);
const Color danappColor6 = Color(0xffF3FAFF);
const Color danappColor7 = Color(0xffFCF4F0);
const Color danappColor8 = Color(0xffF7A325);
const Color danappColor9 = Color(0xffF4F9FF);
const Color danappColor10 = Color(0xffE9FFF0);
const Color danappColor11 = Color(0xff12B76A);
const Color danappColor12 = Color(0xffF4F1F6);
const Color danappColor13 = Color(0xffD1D1D1);
const Color danappColor14 = Color(0xffF8F8F8);
const Color danappColor15 = Color(0xff0184D6);
const Color danappColor16 = Color(0xff4E4E4E);
const Color danappColor17 = Color(0xffF30909);
const Color danappColor18 = Color(0xff009A49);
const Color danappColor19 = Color(0xff59B200);
const Color danappColor20 = Color(0xffD6FFAE);
const Color danappColor21 = Color(0xff646464);
const Color danappColor22 = Color(0xffFFE5BE);
const Color danappColor23 = Color(0xffC0E2FF);
const Color danappColor24 = Color(0xff9EFFCC);
const Color danappColor25 = Color(0xffFF4800);
const Color danappColor26 = Color(0xff242525);
